# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/marlin/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter marlin sailfish, $(TARGET_DEVICE)),)

endif
